// =============================================================================
// Song Metadata — 10. klass
// =============================================================================

var SONGS = [
    { id: 0,  file: "songs/01 - Gregooriuse koraal - _Puer Natus Est Nobis_ (Üks laps on meile sündinud).mp3", number: "01", title: "Puer Natus Est Nobis", composer: "Gregooriuse koraal", type: "koraal" },
    { id: 1,  file: "songs/02 - Gregooriuse koraal - _Veni Creator Spiritus_ (Oh tule Looja vaim).mp3", number: "02", title: "Veni Creator Spiritus", composer: "Gregooriuse koraal", type: "koraal" },
    { id: 2,  file: "songs/03 - Gregooriuse koraal - _Kyrie Eleison_ (Issand halasta), missa esimene muutumatu tekstiga osa.mp3", number: "03", title: "Kyrie Eleison", composer: "Gregooriuse koraal", type: "koraal" },
    { id: 3,  file: "songs/04 - Leoninus - 2-häälne organum _Viderunt omnes_ (Kõik näevad).mp3", number: "04", title: "Viderunt omnes", composer: "Leoninus", type: "organum" },
    { id: 4,  file: "songs/05 - Walther von der Vogelweide - _Palästinalied_ (Palestiina laul).mp3", number: "05", title: "Palästinalied", composer: "Walther von der Vogelweide", type: "laul" },
    { id: 5,  file: "songs/06 - Keskaegne tantsumuusika Prantsusmaalt - _Estampie_.mp3", number: "06", title: "Estampie", composer: "Keskaegne tantsumuusika", type: "tantsumuusika" },
    { id: 6,  file: "songs/07 - 13. sajandi motett  - _Alle psallite cum luya_ (Kõik laulge-mängige rõõmuga).mp3", number: "07", title: "Alle psallite cum luya", composer: "13. sajandi motett", type: "motett" },
    { id: 7,  file: "songs/08 - Philippe de Vitry - Motett _Imprudenter Circumivi_ (Mõistmatult petma).mp3", number: "08", title: "Imprudenter Circumivi", composer: "Philippe de Vitry", type: "motett" },
    { id: 8,  file: "songs/09 - Guillaume de Machaut _Messe de Notre Dame_ (Jumalaema missa), osa _Kyrie_.mp3", number: "09", title: "Messe de Notre Dame, Kyrie", composer: "Guillaume de Machaut", type: "missa" },
    { id: 9,  file: "songs/10 - Guillaume Dufay - Chanson _Se la face ai pale_ (Su nägu on nii kahvatu).mp3", number: "10", title: "Se la face ai pale", composer: "Guillaume Dufay", type: "chanson" },
    { id: 10, file: "songs/11 - Clement Janequin - Chanson _ Le chant des oiseaux_ (Lindude laul) - katkend.mp3", number: "11", title: "Le chant des oiseaux", composer: "Clement Janequin", type: "chanson" },
    { id: 11, file: "songs/12 - Josquin Desprez - Frottola _El Grillo_ (Ritsikas).mp3", number: "12", title: "El Grillo", composer: "Josquin Desprez", type: "frottola" },
    { id: 12, file: "songs/13 - Orlando di Lasso - Madrigal _Matona mia cara_ (Minu armas daam).mp3", number: "13", title: "Matona mia cara", composer: "Orlando di Lasso", type: "madrigal" },
    { id: 13, file: "songs/14 - Renessanssiaegne instrumentaalmuusika Itaaliast - _Saltarella_.mp3", number: "14", title: "Saltarella", composer: "Renessanssiaegne instrumentaalmuusika", type: "tantsumuusika" },
    { id: 14, file: "songs/15 - Martin Luther - Koraal _Üks kindel linn ja varjupaik_, ingliskeelne versioon _A Mighty Fortress is our God_.mp3", number: "15", title: "Üks kindel linn ja varjupaik", composer: "Martin Luther", type: "koraal" },
    { id: 15, file: "songs/16 - Giovanni Pierluigi da Palestrina _Missa Papae Marcelli_ (Paavst Marcelluse missa), osa _Kyrie_.mp3", number: "16", title: "Missa Papae Marcelli, Kyrie", composer: "Giovanni Pierluigi da Palestrina", type: "missa" },
    { id: 16, file: "songs/17 - Giovanni Gabrieli - 15-häälne kontsert _Salvator noster_ (Meie päästja).mp3", number: "17", title: "Salvator noster", composer: "Giovanni Gabrieli", type: "kontsert" },
    { id: 17, file: "songs/18 - Claudio Monteverdi - ooper _Orpheus_, avamäng.mp3", number: "18", title: "Orpheus, avamäng", composer: "Claudio Monteverdi", type: "ooper" },
    { id: 18, file: "songs/19 - Claudio Monteverdi - ooper _Orpheus_, Orpheuse aaria _Possente spirto_ (Oo jumalad, allilma valitsejad).mp3", number: "19", title: "Possente spirto", composer: "Claudio Monteverdi", type: "ooper" },
    { id: 19, file: "songs/20 - Arcangelo Corelli - Concerto Grosso op.6, nr. 8 (_Jõuluöö kontsert_), I osa - Vivace.mp3", number: "20", title: "Concerto Grosso, Jõuluöö kontsert", composer: "Arcangelo Corelli", type: "concerto grosso" },
    { id: 20, file: "songs/21 - Antonio Vivaldi - Viiulikontsertide tsükkel _Aastaajad_, Kontsert  nr. 1 _Kevad_, I osa - Allegro.mp3", number: "21", title: "Aastaajad: Kevad, I osa", composer: "Antonio Vivaldi", type: "viiulikontsert" },
    { id: 21, file: "songs/22 - Antonio Vivaldi - Viiulikontsertide tsükkel _Aastaajad_, Kontsert  nr.2 _Suvi_, II osa - Adagio - Presto.mp3", number: "22", title: "Aastaajad: Suvi, II osa", composer: "Antonio Vivaldi", type: "viiulikontsert" },
    { id: 22, file: "songs/23 - Antonio Vivaldi - Viiulikontsertide tsükkel _Aastaajad_, Kontsert  nr. 3 _Sügis_, III osa - Allegro.mp3", number: "23", title: "Aastaajad: Sügis, III osa", composer: "Antonio Vivaldi", type: "viiulikontsert" },
    { id: 23, file: "songs/24 - Jean-Baptiste Lully - ballett-komöödia _Le Bourgeois Gentilhomme_ (Kodanlasest aadlimees), Türklaste marss.mp3", number: "24", title: "Le Bourgeois Gentilhomme, Türklaste marss", composer: "Jean-Baptiste Lully", type: "ballett-komöödia" },
    { id: 24, file: "songs/25 - Henry Purcell - muusika näidendile _Abdelazar_ (Mauri kättemaks), Rondo.mp3", number: "25", title: "Abdelazar, Rondo", composer: "Henry Purcell", type: "näidendimuusika" },
    { id: 25, file: "songs/26 - Johann Sebastian Bach - Prelüüd ja fuuga C-duur, kogumikust _Hästitempereeritud klaviir_.mp3", number: "26", title: "Prelüüd ja fuuga C-duur", composer: "Johann Sebastian Bach", type: "klaverimuusika" },
    { id: 26, file: "songs/27 - Johann Sebastian Bach - _Tokaata ja fuuga d-moll_, orelile.mp3", number: "27", title: "Tokaata ja fuuga d-moll", composer: "Johann Sebastian Bach", type: "oreliteos" },
    { id: 27, file: "songs/28 - Johann Sebastian Bach - _Brandenburgi kontsert_ nr.5, I osa - Allegro (katkend).mp3", number: "28", title: "Brandenburgi kontsert nr. 5, I osa", composer: "Johann Sebastian Bach", type: "kontsert" },
    { id: 28, file: "songs/29 - Johann Sebastian Bach - _Missa h-moll_, osa _Sanctus_.mp3", number: "29", title: "Missa h-moll, Sanctus", composer: "Johann Sebastian Bach", type: "missa" },
    { id: 29, file: "songs/30 - Johann Sebastian Bach - _Matteuse passioon_, aaria _Erbarme dich_ (Halasta, mu Jumal, mu pisarate pärast).mp3", number: "30", title: "Erbarme dich", composer: "Johann Sebastian Bach", type: "passioon" },
    { id: 30, file: "songs/31 - Johann Sebastian Bach - _Matteuse passioon_, koraal _Befiehl du deine Wege_ (Oh püha pea täis verd ja haavu).mp3", number: "31", title: "Befiehl du deine Wege", composer: "Johann Sebastian Bach", type: "passioon" },
    { id: 31, file: "songs/32 - Georg Friedrich Händel - kroonimishümn _Zadok the Priest_ (Preester Zadok).mp3", number: "32", title: "Zadok the Priest", composer: "Georg Friedrich Händel", type: "kroonimishümn" },
    { id: 32, file: "songs/33 - Georg Friedrich Händel - orkestrisüit _Veemuusika_, IV osa _Hornpipe_.mp3", number: "33", title: "Veemuusika, Hornpipe", composer: "Georg Friedrich Händel", type: "orkestrisüit" },
    { id: 33, file: "songs/34 - Georg Friedrich Händel - ooper _Rodelinda_, Bertarido aaria _Vivi tiranno_ (Elagu türann).mp3", number: "34", title: "Vivi tiranno", composer: "Georg Friedrich Händel", type: "ooper" },
    { id: 34, file: "songs/35 - Georg Friedrich Händel - oratoorium _Messias_, koor _Halleluja_.mp3", number: "35", title: "Halleluja", composer: "Georg Friedrich Händel", type: "oratoorium" },
    { id: 35, file: "songs/36 - Christoph Willibald Gluck - ooper _Orfeus ja Euridice_, Orfeuse aaria _Che faro senza Euridice_.mp3", number: "36", title: "Che faro senza Euridice", composer: "Christoph Willibald Gluck", type: "ooper" },
    { id: 36, file: "songs/37 - Franz Joseph Haydn - Sümfoonia nr. 94 _Üllatussümfoonia_, II osa - Andante.mp3", number: "37", title: "Sümfoonia nr. 94, Üllatussümfoonia", composer: "Franz Joseph Haydn", type: "sümfoonia" },
    { id: 37, file: "songs/38 - Franz Joseph Haydn Trompetikontsert Es-duur III osa - Allegro.mp3", number: "38", title: "Trompetikontsert Es-duur, III osa", composer: "Franz Joseph Haydn", type: "kontsert" },
    { id: 38, file: "songs/39 - Wolfgang Amadeus Mozart - Sümfoonia nr. 40, I osa - Allegro molto.mp3", number: "39", title: "Sümfoonia nr. 40, I osa", composer: "Wolfgang Amadeus Mozart", type: "sümfoonia" },
    { id: 39, file: "songs/40 - Wolfgang Amadeus Mozart - Klaverikontsert nr. 21 _Elvira Madigan_, II osa - Andante.mp3", number: "40", title: "Klaverikontsert nr. 21, Elvira Madigan", composer: "Wolfgang Amadeus Mozart", type: "klaverikontsert" },
    { id: 40, file: "songs/41 - Wolfgang Amadeus Mozart - ooper _Võluflööt_, Papageno aaria _Der Vogelfänger bin ich ja_ (Olen linnukaupleja).mp3", number: "41", title: "Der Vogelfänger bin ich ja", composer: "Wolfgang Amadeus Mozart", type: "ooper" },
    { id: 41, file: "songs/42 - Wolfgang Amadeus Mozart - _Reekviem_, osa _Dies Irae_ (Viha päev).mp3", number: "42", title: "Dies Irae", composer: "Wolfgang Amadeus Mozart", type: "reekviem" },
    { id: 42, file: "songs/43 - Ludwig van Beethoven - Sonaat nr. 14 _Kuupaiste_, I osa - Adagio.mp3", number: "43", title: "Sonaat nr. 14, Kuupaiste", composer: "Ludwig van Beethoven", type: "klaverisonaat" },
    { id: 43, file: "songs/44 - Ludwig van Beethoven - Sümfoonia nr. 5 _Saatuse_, I osa - Allegro con brio.mp3", number: "44", title: "Sümfoonia nr. 5, Saatuse", composer: "Ludwig van Beethoven", type: "sümfoonia" },
    { id: 44, file: "songs/45 - Ludwig van Beethoven - Sümfoonia nr. 9, IV osa - lõpukoor _Ood rõõmule_.mp3", number: "45", title: "Ood rõõmule", composer: "Ludwig van Beethoven", type: "sümfoonia" }
];
